import type {
  Brand,
  Department,
  User,
  Project,
  Task,
  WorkflowTemplate,
  WorkflowInstance,
  Notification,
  SystemRole,
} from "./types";

// ─── Brands ──────────────────────────────────────────────────────────────────
export const brands: Brand[] = [
  { id: "danfe", name: "Danfe Tea", initials: "DT", color: "bg-accent text-accent-foreground" },
  { id: "nte", name: "Nepal Tea Exchange", initials: "NT", color: "bg-primary/15 text-primary" },
];

// ─── Departments ─────────────────────────────────────────────────────────────
export const departments: Department[] = [
  { id: "seo", name: "SEO", teamLeadId: "u4", brandIds: ["danfe", "nte"] },
  { id: "social_media", name: "Social Media", teamLeadId: "u2", brandIds: ["danfe", "nte"] },
  { id: "graphic_design", name: "Graphic Design", teamLeadId: "u3", brandIds: ["danfe", "nte"] },
  {
    id: "videography",
    name: "Videography / Video Editing",
    teamLeadId: "u5",
    brandIds: ["danfe", "nte"],
  },
];

// ─── Users ───────────────────────────────────────────────────────────────────
export const users: User[] = [
  {
    id: "u1",
    name: "Pratik R.",
    email: "pratik@danfetea.com",
    initials: "PR",
    role: "admin",
    departmentId: "seo",
    brandIds: ["danfe", "nte"],
    avatarColor: "bg-primary/15 text-primary",
  },
  {
    id: "u2",
    name: "Sita R.",
    email: "sita@danfetea.com",
    initials: "SR",
    role: "team_lead",
    departmentId: "social_media",
    brandIds: ["danfe", "nte"],
    avatarColor: "bg-accent text-accent-foreground",
  },
  {
    id: "u3",
    name: "Meera K.",
    email: "meera@danfetea.com",
    initials: "MK",
    role: "team_lead",
    departmentId: "graphic_design",
    brandIds: ["danfe", "nte"],
    avatarColor: "bg-success/15 text-success",
  },
  {
    id: "u4",
    name: "Aakash S.",
    email: "aakash@danfetea.com",
    initials: "AS",
    role: "team_lead",
    departmentId: "seo",
    brandIds: ["danfe"],
    avatarColor: "bg-info/15 text-info",
  },
  {
    id: "u5",
    name: "Sneha P.",
    email: "sneha@danfetea.com",
    initials: "SP",
    role: "team_lead",
    departmentId: "videography",
    brandIds: ["nte"],
    avatarColor: "bg-warning/20 text-warning-foreground",
  },
  {
    id: "u6",
    name: "Ravi T.",
    email: "ravi@danfetea.com",
    initials: "RT",
    role: "team_member",
    departmentId: "social_media",
    brandIds: ["danfe", "nte"],
    avatarColor: "bg-destructive/10 text-destructive",
  },
  {
    id: "u7",
    name: "Anita M.",
    email: "anita@danfetea.com",
    initials: "AM",
    role: "team_member",
    departmentId: "graphic_design",
    brandIds: ["danfe"],
    avatarColor: "bg-primary/15 text-primary",
  },
  {
    id: "u8",
    name: "Bikash G.",
    email: "bikash@danfetea.com",
    initials: "BG",
    role: "team_member",
    departmentId: "seo",
    brandIds: ["nte"],
    avatarColor: "bg-accent text-accent-foreground",
  },
  {
    id: "u9",
    name: "Deepa S.",
    email: "deepa@danfetea.com",
    initials: "DS",
    role: "team_member",
    departmentId: "videography",
    brandIds: ["danfe", "nte"],
    avatarColor: "bg-success/15 text-success",
  },
  {
    id: "u10",
    name: "Kiran P.",
    email: "kiran@danfetea.com",
    initials: "KP",
    role: "team_member",
    departmentId: "social_media",
    brandIds: ["danfe"],
    avatarColor: "bg-info/15 text-info",
  },
];

// ─── Projects ────────────────────────────────────────────────────────────────
export const projects: Project[] = [
  {
    id: "p1",
    name: "Dashain Campaign 2026",
    description: "Full campaign for Dashain festival across all channels",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-06-01",
  },
  {
    id: "p2",
    name: "Instagram Content Q3",
    description: "Instagram content calendar and posting",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-06-15",
  },
  {
    id: "p3",
    name: "Christmas Campaign",
    description: "Christmas and year-end promotional campaign",
    brandId: "nte",
    status: "active",
    createdAt: "2026-07-01",
  },
  {
    id: "p4",
    name: "Website SEO Optimization",
    description: "SEO improvements for both brand websites",
    brandId: "nte",
    status: "active",
    createdAt: "2026-05-20",
  },
  {
    id: "p5",
    name: "Product Photography",
    description: "New product line photography for catalog",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-07-10",
  },
];

// ─── Workflow Templates ──────────────────────────────────────────────────────
export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: "wf1",
    name: "Instagram Story Posting",
    description: "End-to-end workflow for creating and posting Instagram stories",
    departmentId: "social_media",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-06-01",
    usageCount: 24,
    steps: [
      {
        id: "s1",
        name: "Design Story",
        description: "Create the visual design for the story",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "4h",
        deadline: "+1d",
        checklist: [
          { id: "c1", label: "Follow brand guidelines" },
          { id: "c2", label: "Use correct dimensions" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s2",
        name: "Review Design",
        description: "Team lead reviews the design",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [{ id: "c3", label: "Check brand consistency" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s3",
        name: "Upload Story",
        description: "Upload and schedule the story on Instagram",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "1h",
        deadline: "+0.5d",
        checklist: [
          { id: "c4", label: "Add captions" },
          { id: "c5", label: "Add hashtags" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
      {
        id: "s4",
        name: "Quality Check",
        description: "Verify the story is live and correct",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "0.5h",
        deadline: "+0.5d",
        checklist: [{ id: "c6", label: "Verify link works" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 550 },
      },
    ],
    connections: [
      { id: "conn1", from: "s1", to: "s2" },
      { id: "conn2", from: "s2", to: "s3" },
      { id: "conn3", from: "s3", to: "s4" },
    ],
  },
  {
    id: "wf2",
    name: "SEO Blog Publishing",
    description: "Research, write, optimize, and publish SEO blog posts",
    departmentId: "seo",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-05-15",
    usageCount: 18,
    steps: [
      {
        id: "s5",
        name: "Keyword Research",
        description: "Research target keywords and search intent",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "3h",
        deadline: "+1d",
        checklist: [
          { id: "c7", label: "Identify primary keyword" },
          { id: "c8", label: "Find LSI keywords" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s6",
        name: "Write Content",
        description: "Write the blog post content",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "8h",
        deadline: "+3d",
        checklist: [
          { id: "c9", label: "Follow content brief" },
          { id: "c10", label: "Include target keywords" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s7",
        name: "Content Review",
        description: "Review content for quality and SEO",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [{ id: "c11", label: "Check readability" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
      {
        id: "s8",
        name: "Publish",
        description: "Publish the blog post on the website",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "1h",
        deadline: "+0.5d",
        checklist: [
          { id: "c12", label: "Add meta tags" },
          { id: "c13", label: "Set featured image" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 550 },
      },
    ],
    connections: [
      { id: "conn4", from: "s5", to: "s6" },
      { id: "conn5", from: "s6", to: "s7" },
      { id: "conn6", from: "s7", to: "s8" },
    ],
  },
  {
    id: "wf3",
    name: "Facebook Ad Campaign",
    description: "Create and launch Facebook ad campaigns",
    departmentId: "social_media",
    brandId: "nte",
    status: "active",
    createdAt: "2026-06-10",
    usageCount: 12,
    steps: [
      {
        id: "s9",
        name: "Ad Brief",
        description: "Create advertising brief and objectives",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "2h",
        deadline: "+1d",
        checklist: [
          { id: "c14", label: "Define audience" },
          { id: "c15", label: "Set budget" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s10",
        name: "Design Ad Creatives",
        description: "Design images and copy for the ad",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "6h",
        deadline: "+2d",
        checklist: [{ id: "c16", label: "Create 3 variations" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s11",
        name: "Review & Approve",
        description: "Review ad creatives and copy",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [{ id: "c17", label: "Check compliance" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
      {
        id: "s12",
        name: "Launch Campaign",
        description: "Set up and launch the campaign on Facebook",
        departmentId: "social_media",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "1h",
        deadline: "+0.5d",
        checklist: [
          { id: "c18", label: "Set targeting" },
          { id: "c19", label: "Schedule posts" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 550 },
      },
    ],
    connections: [
      { id: "conn7", from: "s9", to: "s10" },
      { id: "conn8", from: "s10", to: "s11" },
      { id: "conn9", from: "s11", to: "s12" },
    ],
  },
  {
    id: "wf4",
    name: "Product Photography",
    description: "Product photography shoot and editing workflow",
    departmentId: "graphic_design",
    brandId: "danfe",
    status: "active",
    createdAt: "2026-07-01",
    usageCount: 8,
    steps: [
      {
        id: "s13",
        name: "Shot List",
        description: "Prepare shot list and references",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "2h",
        deadline: "+1d",
        checklist: [{ id: "c20", label: "List all products" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s14",
        name: "Photo Shoot",
        description: "Conduct the product photography session",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "8h",
        deadline: "+2d",
        checklist: [
          { id: "c21", label: "Set up lighting" },
          { id: "c22", label: "Capture all angles" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s15",
        name: "Edit Photos",
        description: "Post-process and retouch photos",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "6h",
        deadline: "+2d",
        checklist: [
          { id: "c23", label: "Color correct" },
          { id: "c24", label: "Remove background" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
      {
        id: "s16",
        name: "Final Approval",
        description: "Review final images",
        departmentId: "graphic_design",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "1h",
        deadline: "+0.5d",
        checklist: [{ id: "c25", label: "Check resolution" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 550 },
      },
    ],
    connections: [
      { id: "conn10", from: "s13", to: "s14" },
      { id: "conn11", from: "s14", to: "s15" },
      { id: "conn12", from: "s15", to: "s16" },
    ],
  },
  {
    id: "wf5",
    name: "Monthly Report",
    description: "Generate monthly performance report across departments",
    departmentId: "seo",
    brandId: "danfe",
    status: "archived",
    createdAt: "2026-04-01",
    usageCount: 6,
    steps: [
      {
        id: "s17",
        name: "Collect Data",
        description: "Gather metrics from all channels",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "4h",
        deadline: "+2d",
        checklist: [
          { id: "c26", label: "SEO metrics" },
          { id: "c27", label: "Social metrics" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s18",
        name: "Create Report",
        description: "Compile data into report format",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "4h",
        deadline: "+1d",
        checklist: [{ id: "c28", label: "Use template" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s19",
        name: "Review Report",
        description: "Manager reviews the report",
        departmentId: "seo",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [{ id: "c29", label: "Check accuracy" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
    ],
    connections: [
      { id: "conn13", from: "s17", to: "s18" },
      { id: "conn14", from: "s18", to: "s19" },
    ],
  },
  {
    id: "wf6",
    name: "Video Editing Pipeline",
    description: "Edit, review, and publish video content",
    departmentId: "videography",
    brandId: "nte",
    status: "active",
    createdAt: "2026-06-20",
    usageCount: 10,
    steps: [
      {
        id: "s20",
        name: "Raw Footage Review",
        description: "Review and select best footage",
        departmentId: "videography",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "3h",
        deadline: "+1d",
        checklist: [{ id: "c30", label: "Select best clips" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 100 },
      },
      {
        id: "s21",
        name: "Edit Video",
        description: "Cut, arrange, and add effects",
        departmentId: "videography",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "12h",
        deadline: "+3d",
        checklist: [
          { id: "c31", label: "Add transitions" },
          { id: "c32", label: "Color grade" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 250 },
      },
      {
        id: "s22",
        name: "Review Edit",
        description: "Review the edited video",
        departmentId: "videography",
        assignedUserId: null,
        approvalRequired: true,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [{ id: "c33", label: "Check audio sync" }],
        attachments: [],
        comments: [],
        position: { x: 100, y: 400 },
      },
      {
        id: "s23",
        name: "Export & Publish",
        description: "Export final video and publish",
        departmentId: "videography",
        assignedUserId: null,
        approvalRequired: false,
        estimatedTime: "2h",
        deadline: "+0.5d",
        checklist: [
          { id: "c34", label: "Export in correct format" },
          { id: "c35", label: "Upload to platform" },
        ],
        attachments: [],
        comments: [],
        position: { x: 100, y: 550 },
      },
    ],
    connections: [
      { id: "conn15", from: "s20", to: "s21" },
      { id: "conn16", from: "s21", to: "s22" },
      { id: "conn17", from: "s22", to: "s23" },
    ],
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const tasks: Task[] = [
  {
    id: "t1",
    title: "Design Instagram Story for Dashain",
    description:
      "Create a visually appealing Instagram story for the Dashain campaign. Follow brand guidelines and use festive colors.",
    status: "in_progress",
    priority: "high",
    brandId: "danfe",
    projectId: "p1",
    departmentId: "graphic_design",
    workflowId: "wf1",
    workflowStepIndex: 0,
    assignedTo: "u7",
    approvedBy: null,
    dueDate: "2026-07-28",
    estimatedTime: "4h",
    checklist: [
      { id: "cl1", label: "Follow brand guidelines", checked: true },
      { id: "cl2", label: "Use correct dimensions (1080x1920)", checked: true },
      { id: "cl3", label: "Include festive elements", checked: false },
    ],
    attachments: [
      {
        id: "a1",
        name: "dashain-moodboard.pdf",
        type: "document",
        size: "2.4 MB",
        uploadedBy: "u2",
        uploadedAt: "2026-07-25T10:00:00Z",
        version: 1,
      },
    ],
    comments: [
      {
        id: "cm1",
        userId: "u2",
        text: "Please use the gold and red palette from the brand kit.",
        createdAt: "2026-07-25T11:00:00Z",
      },
    ],
    activities: [
      {
        id: "act1",
        action: "workflow_started",
        userId: "u1",
        description: "Workflow 'Instagram Story Posting' started",
        timestamp: "2026-07-25T09:00:00Z",
      },
      {
        id: "act2",
        action: "task_assigned",
        userId: "u1",
        description: "Task assigned to Anita M.",
        timestamp: "2026-07-25T09:01:00Z",
      },
      {
        id: "act3",
        action: "files_uploaded",
        userId: "u2",
        description: "Sita uploaded dashain-moodboard.pdf",
        timestamp: "2026-07-25T10:00:00Z",
      },
      {
        id: "act4",
        action: "comment_added",
        userId: "u2",
        description: "Sita commented on the task",
        timestamp: "2026-07-25T11:00:00Z",
      },
    ],
    approvalRequired: false,
    submittedAt: null,
    reviewedAt: null,
  },
  {
    id: "t2",
    title: "Review Dashain Story Design",
    description:
      "Review the Instagram story design for the Dashain campaign. Check brand consistency and visual appeal.",
    status: "ready",
    priority: "high",
    brandId: "danfe",
    projectId: "p1",
    departmentId: "social_media",
    workflowId: "wf1",
    workflowStepIndex: 1,
    assignedTo: "u2",
    approvedBy: null,
    dueDate: "2026-07-29",
    estimatedTime: "2h",
    checklist: [
      { id: "cl4", label: "Check brand consistency", checked: false },
      { id: "cl5", label: "Verify messaging", checked: false },
    ],
    attachments: [],
    comments: [],
    activities: [],
    approvalRequired: true,
    submittedAt: null,
    reviewedAt: null,
  },
  {
    id: "t3",
    title: "Write SEO Blog: Best Nepali Teas",
    description:
      "Write a comprehensive blog post about the best Nepali teas for the company blog. Target keyword: 'best nepali tea'.",
    status: "in_progress",
    priority: "medium",
    brandId: "danfe",
    projectId: "p4",
    departmentId: "seo",
    workflowId: "wf2",
    workflowStepIndex: 1,
    assignedTo: "u8",
    approvedBy: null,
    dueDate: "2026-07-30",
    estimatedTime: "8h",
    checklist: [
      { id: "cl6", label: "Follow content brief", checked: true },
      { id: "cl7", label: "Include target keywords naturally", checked: true },
      { id: "cl8", label: "Add internal links", checked: false },
      { id: "cl9", label: "Write meta description", checked: false },
    ],
    attachments: [
      {
        id: "a2",
        name: "content-brief.docx",
        type: "document",
        size: "156 KB",
        uploadedBy: "u4",
        uploadedAt: "2026-07-24T08:00:00Z",
        version: 1,
      },
    ],
    comments: [
      {
        id: "cm2",
        userId: "u4",
        text: "Focus on organic search intent. Include comparisons with Indian teas.",
        createdAt: "2026-07-24T09:00:00Z",
      },
    ],
    activities: [],
    approvalRequired: false,
    submittedAt: null,
    reviewedAt: null,
  },
  {
    id: "t4",
    title: "Design Christmas Ad Creatives",
    description: "Design 3 variations of Facebook ad creatives for the Christmas campaign.",
    status: "ready",
    priority: "high",
    brandId: "nte",
    projectId: "p3",
    departmentId: "graphic_design",
    workflowId: "wf3",
    workflowStepIndex: 1,
    assignedTo: "u3",
    approvedBy: null,
    dueDate: "2026-08-01",
    estimatedTime: "6h",
    checklist: [
      { id: "cl10", label: "Create 3 variations", checked: false },
      { id: "cl11", label: "Include product shots", checked: false },
      { id: "cl12", label: "Add promotional text", checked: false },
    ],
    attachments: [],
    comments: [],
    activities: [],
    approvalRequired: false,
    submittedAt: null,
    reviewedAt: null,
  },
  {
    id: "t5",
    title: "Edit Product Showcase Video",
    description:
      "Edit the raw footage for the new product showcase video. Add transitions, music, and brand elements.",
    status: "waiting_review",
    priority: "medium",
    brandId: "nte",
    projectId: "p5",
    departmentId: "videography",
    workflowId: "wf6",
    workflowStepIndex: 2,
    assignedTo: "u5",
    approvedBy: null,
    dueDate: "2026-07-29",
    estimatedTime: "2h",
    checklist: [
      { id: "cl13", label: "Check audio sync", checked: true },
      { id: "cl14", label: "Verify color grading", checked: true },
    ],
    attachments: [
      {
        id: "a3",
        name: "product-showcase-draft.mp4",
        type: "video",
        size: "145 MB",
        uploadedBy: "u5",
        uploadedAt: "2026-07-26T14:00:00Z",
        version: 1,
      },
    ],
    comments: [],
    activities: [],
    approvalRequired: true,
    submittedAt: "2026-07-26T14:00:00Z",
    reviewedAt: null,
  },
  {
    id: "t6",
    title: "Keyword Research for Q4 Content",
    description:
      "Research target keywords for Q4 content calendar. Focus on holiday-related search terms.",
    status: "completed",
    priority: "medium",
    brandId: "danfe",
    projectId: "p4",
    departmentId: "seo",
    workflowId: "wf2",
    workflowStepIndex: 0,
    assignedTo: "u4",
    approvedBy: "u1",
    dueDate: "2026-07-25",
    estimatedTime: "3h",
    checklist: [
      { id: "cl15", label: "Identify primary keywords", checked: true },
      { id: "cl16", label: "Find LSI keywords", checked: true },
      { id: "cl17", label: "Analyze competitor keywords", checked: true },
    ],
    attachments: [
      {
        id: "a4",
        name: "q4-keywords.xlsx",
        type: "document",
        size: "89 KB",
        uploadedBy: "u4",
        uploadedAt: "2026-07-24T16:00:00Z",
        version: 1,
      },
    ],
    comments: [],
    activities: [],
    approvalRequired: false,
    submittedAt: "2026-07-24T16:00:00Z",
    reviewedAt: "2026-07-25T09:00:00Z",
  },
  {
    id: "t7",
    title: "Schedule Instagram Posts for Next Week",
    description:
      "Schedule all planned Instagram posts for the upcoming week using the content calendar.",
    status: "ready",
    priority: "low",
    brandId: "danfe",
    projectId: "p2",
    departmentId: "social_media",
    workflowId: "wf1",
    workflowStepIndex: 2,
    assignedTo: "u6",
    approvedBy: null,
    dueDate: "2026-08-01",
    estimatedTime: "1h",
    checklist: [],
    attachments: [],
    comments: [],
    activities: [],
    approvalRequired: false,
    submittedAt: null,
    reviewedAt: null,
  },
  {
    id: "t8",
    title: "Film Tea Production Process",
    description: "Capture video footage of the tea production process for the brand documentary.",
    status: "in_progress",
    priority: "high",
    brandId: "danfe",
    projectId: "p5",
    departmentId: "videography",
    workflowId: "wf6",
    workflowStepIndex: 0,
    assignedTo: "u9",
    approvedBy: null,
    dueDate: "2026-07-31",
    estimatedTime: "8h",
    checklist: [
      { id: "cl18", label: "Set up lighting", checked: true },
      { id: "cl19", label: "Capture all stages", checked: false },
      { id: "cl20", label: "Record interviews", checked: false },
    ],
    attachments: [],
    comments: [],
    activities: [],
    approvalRequired: false,
    submittedAt: null,
    reviewedAt: null,
  },
];

// ─── Workflow Instances ──────────────────────────────────────────────────────
export const workflowInstances: WorkflowInstance[] = [
  {
    id: "wi1",
    templateId: "wf1",
    projectId: "p1",
    brandId: "danfe",
    status: "running",
    currentStepIndex: 1,
    startedAt: "2026-07-25T09:00:00Z",
    startedBy: "u1",
  },
  {
    id: "wi2",
    templateId: "wf2",
    projectId: "p4",
    brandId: "danfe",
    status: "running",
    currentStepIndex: 1,
    startedAt: "2026-07-23T08:00:00Z",
    startedBy: "u1",
  },
  {
    id: "wi3",
    templateId: "wf6",
    projectId: "p5",
    brandId: "nte",
    status: "running",
    currentStepIndex: 0,
    startedAt: "2026-07-26T07:00:00Z",
    startedBy: "u1",
  },
];

// ─── Notifications ───────────────────────────────────────────────────────────
export const notifications: Notification[] = [
  {
    id: "n1",
    type: "task_assigned",
    title: "Task Assigned",
    message: "You have been assigned 'Design Instagram Story for Dashain'",
    taskId: "t1",
    userId: "u7",
    read: false,
    createdAt: "2026-07-25T09:01:00Z",
  },
  {
    id: "n2",
    type: "waiting_review",
    title: "Waiting for Review",
    message: "'Edit Product Showcase Video' is waiting for your review",
    taskId: "t5",
    userId: "u1",
    read: false,
    createdAt: "2026-07-26T14:00:00Z",
  },
  {
    id: "n3",
    type: "task_submitted",
    title: "Task Submitted",
    message: "Sneha submitted 'Edit Product Showcase Video' for review",
    taskId: "t5",
    userId: "u1",
    read: false,
    createdAt: "2026-07-26T14:00:00Z",
  },
  {
    id: "n4",
    type: "task_due_today",
    title: "Task Due Today",
    message: "'Design Instagram Story for Dashain' is due today",
    taskId: "t1",
    userId: "u7",
    read: true,
    createdAt: "2026-07-28T08:00:00Z",
  },
  {
    id: "n5",
    type: "workflow_started",
    title: "Workflow Started",
    message: "Workflow 'Instagram Story Posting' has been started for Dashain Campaign",
    taskId: null,
    userId: "u1",
    read: true,
    createdAt: "2026-07-25T09:00:00Z",
  },
  {
    id: "n6",
    type: "task_approved",
    title: "Task Approved",
    message: "'Keyword Research for Q4 Content' has been approved",
    taskId: "t6",
    userId: "u4",
    read: true,
    createdAt: "2026-07-25T09:00:00Z",
  },
  {
    id: "n7",
    type: "revision_requested",
    title: "Revision Requested",
    message: "Sita requested changes on 'October campaign brief'",
    taskId: null,
    userId: "u3",
    read: false,
    createdAt: "2026-07-24T15:00:00Z",
  },
  {
    id: "n8",
    type: "task_overdue",
    title: "Task Overdue",
    message: "'Vendor onboarding checklist' is overdue by 1 day",
    taskId: null,
    userId: "u6",
    read: false,
    createdAt: "2026-07-27T08:00:00Z",
  },
];

// ─── Helper Functions ────────────────────────────────────────────────────────
export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function getBrandById(id: string): Brand | undefined {
  return brands.find((b) => b.id === id);
}

export function getDepartmentById(id: string): Department | undefined {
  return departments.find((d) => d.id === id);
}

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export function getTasksForUser(userId: string, brandId?: string): Task[] {
  return tasks.filter((t) => {
    const matchesUser = t.assignedTo === userId;
    const matchesBrand = brandId ? t.brandId === brandId : true;
    return matchesUser && matchesBrand;
  });
}

export function getTasksForBrand(brandId: string): Task[] {
  return tasks.filter((t) => t.brandId === brandId);
}

export function getTasksForDepartment(departmentId: string, brandId?: string): Task[] {
  return tasks.filter((t) => {
    const matchesDept = t.departmentId === departmentId;
    const matchesBrand = brandId ? t.brandId === brandId : true;
    return matchesDept && matchesBrand;
  });
}

export function getNotificationsForUser(userId: string): Notification[] {
  return notifications.filter((n) => n.userId === userId);
}

export function getUnreadCount(userId: string): number {
  return notifications.filter((n) => n.userId === userId && !n.read).length;
}

export function getProjectsForBrand(brandId: string): Project[] {
  return projects.filter((p) => p.brandId === brandId);
}

export function getWorkflowsForBrand(brandId: string): WorkflowTemplate[] {
  return workflowTemplates.filter((w) => w.brandId === brandId);
}

export function getWorkflowTemplateById(id: string): WorkflowTemplate | undefined {
  return workflowTemplates.find((w) => w.id === id);
}
